#!/bin/bash -eu

# start the spark and friends services
docker compose up -d


# open the browser on the jypterlab notebook. 

# keep trying until the URL is available

url=`docker logs spark-lab 2>&1 |  grep "http://127.0.0.1:8888/"  | tail -1 | cut -c 9- `
while [[ -z "$url" ]]
do
    echo "waiting for the container to be ready...."
    sleep 2
    url=`docker logs spark-lab 2>&1 |  grep "http://127.0.0.1:8888/"  | tail -1 | cut -c 9- `
done

echo Try to automatically open the URL
echo If the browser is not opened, Open browser on
    echo $url
set +eu
if [[ -n "$IS_WSL" || -n "$WSL_DISTRO_NAME" ]]; then
    echo "Runing in Windows WSL"
    cmd.exe /C start $url
else
    echo "Running on non WSL machine. Probably Mac or linux"
    uname -a  |grep -i darwin > /dev/null
    isMacos=$?
    if [ $isMacos == 0 ]; then
        open $url
    else
        # This works only in Linux
        xdg-open $url
    fi
fi



